version: '2'

services:
  nginx:
    image: lagun4ik/docker-nginx-pagespeed
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./sites-enabled:/etc/nginx/sites-enabled
      - ./www/:/var/www/
      - ./cache/ngx_pagespeed_cache:/var/cache/ngx_pagespeed_cache
