version: '2'

services:
  nginx:
    image: lagun4ik/nginx-pagespeed
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./sites-enabled:/etc/nginx/sites-enabled
      - ./cache/ngx_pagespeed:/var/cache/ngx_pagespeed
