version: '2'

services:
  nginx:
    image: crunchgeek/nginx-pagespeed
    restart: always
    ports:
      - "80:80"
    hostname: ${HOST_NAME}-nginx
    container_name: nginx
    volumes:
      - ${APPLICATIONS}:/applications:ro
      - ./HEALTHCHECK:/var/www/HEALTHCHECK:ro
