version: "3"

services:
  nginx:
    build: .
    #image: crunchgeek/nginx-pagespeed
    image: 8ear/nginx-pagespeed
    container_name: nginx-pagespeed
    ports:
      - "80:80"
      - "8080:8080"
    restart: unless-stopped
    env_file: docker-compose.env
    # Overwrite default command to start default wordpress template
    command: /bin/sh -c "envsubst '$${WWWROOT} $${PHPBACKEND}'< /etc/nginx/conf.d/default-wp.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    volumes:
    - wp_data:/var/www/html
